const Demodata=[
    {   id:"1",
        image:"https://qph.fs.quoracdn.net/main-qimg-a9054675b70e720a8a933b8b8ca8adf2",
        titles:"Kumbalangi Nights",
        details:"Action",
    },
    {   id:"2",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxx_Rkt_uQEZJTRcLBmMlpWiDZlfESOletMQ&usqp=CAU",
        titles:"Adi ",
        details:"Family",
    },
    {   id:"3",
        image:"https://www.nowrunning.com/content/movie/2023/mahar-27037/bg3.jpg",
        titles:"Maharani",
        details:"Drama/Comedy ",
    },
    {   id:"4",
        image:"https://onlookersmedia.in/wp-content/uploads/2019/08/Kumbalangi-Nights-Poster-Still.jpg",
        titles:"Kumbalangi Nights",
        details:"Romance/Drama",
    },
    {   id:"5",
        image:"https://images.ottplay.com/articles/2023q3/1001_Nunakal_review_OTTplay_critics_cover_image_1_576.jpeg?impolicy=ottplay-20210210&width=350&height=200",
        titles:"Incredible action",
        details:"Tadeas izo",
    },
    {   id:"6",
        image:"https://www.moviesavailableon.com/Images/movies/aanum_pennum_m.jpg",
        titles:"1001 Nunakal",
        details:"Drama",
    },
]
export default Demodata;