const Smallbox=[
    {   id:"1",
        image:"https://assets.gadgets360cdn.com/pricee/assets/product/202306/Kazhuvethi-Moorkkan_1686725842.jpg",
        titles:"Incredible action",
        details:"Tadeas izo",
    },
    {   id:"2",
        image:"https://static.toiimg.com/thumb/width-400,resizemode-4,msid-88771535/88771535.jpg",
        titles:"Incredible action",
        details:"Tadeas izo",
    },
    {   id:"3",
        image:"https://i0.wp.com/img.paisawapas.com/ovz3vew9pw/2023/06/21111252/Tamil-New-Movies-On-OTT-1.jpg?resize=443%2C628&ssl=1",
        titles:"Incredible action",
        details:"Tadeas izo",
    },
    {   id:"4",
        image:"https://assets-in.bmscdn.com/discovery-catalog/events/et00376793-eqdecxvmaa-portrait.jpg",
        titles:"Incredible action",
        details:"Tadeas izo",
    },
    {   id:"5",
        image:"https://www.arrahmanian.com/assets/img/tamil/galatta-kalyaanam.jpg",
        titles:"Incredible action",
        details:"Tadeas izo",
    },
    {   id:"6",
        image:"https://pbs.twimg.com/media/ERDoHy3UUAA0Da5?format=jpg&name=small",
        titles:"Incredible action",
        details:"Tadeas izo",
    },
]
export default Smallbox;